# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST https://http-response-server.vercel.app/analyze
Content-Type: application/json

{
  "url": "https://www.google.com"
}